version: '3'
services:
  sonar:
    build: ./sonar
    depends_on:
      - api
      - ui
      - proxy
  api:
    build: ./api
    volumes:
      - ./api:/api
      - ./secret:/secret
      - ./async-state:/skiff_files/apps/open-scholar/async-state
    environment:
      # This ensures that errors are printed as they occur, which
      # makes debugging easier.
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - MODAL_TOKEN=${MODAL_TOKEN}
      - MODAL_TOKEN_SECRET=${MODAL_TOKEN_SECRET}
      - RETRIEVAL_SERVICE=vespa
      - ASYNC_STATE_DIR=/skiff_files/apps/open-scholar/async-state
    ports:
      - 8000:8000
    env_file:
      - .env
  ui:
    build: ./ui
    # We can't mount the entire UI directory, since JavaScript dependencies
    # (`node_modules`) live at that location.
    volumes:
      - ./ui/src:/ui/src
      - ./ui/public:/ui/public
      - ./ui/package.json:/ui/package.json
      - ./ui/yarn.lock:/ui/yarn.lock
      - ./ui/tsconfig.json:/ui/tsconfig.json
    environment:
      - NODE_ENV=development
    ports:
      - 4000:3000
  proxy:
    build: ./proxy
    ports:
      - 8080:8080
    depends_on:
      - ui
      - api
