import reactToText from 'react-to-text';

import React from 'react';
import { Typography } from '@mui/material';
import styled from 'styled-components';
import Markdown, { MarkdownToJSX } from 'markdown-to-jsx';
import { InlinePaperChipWidgetWithEvidence } from '../widgets/InlinePaperChipWidgetWithEvidence';
import { InlinePaperChipWidgetProps } from '../widgets/InlinePaperChipWidget';
import { ReportSection } from '../../models/Report';


export const Report: React.FC<{ section: ReportSection }> = (props) => {
  const { section } = props;

  const id2Snippets: { [id: string]: string[] } = {};
  section.citations?.forEach((citation) => {
    id2Snippets[citation.id] = citation.snippets;
  });

  const markdownOptions: MarkdownToJSX.Options = {
    overrides: {
      p: {
        component: (props) => <Typography {...props} />,
        props: { paragraph: true, variant: 'body1' },
      },
      Paper: {
        component: (props: Partial<InlinePaperChipWidgetProps>) => {
          const { corpusId, paperTitle, children, fullTitle, id, ...rest } = props;
          let paperTitleStr = paperTitle;
          if (!paperTitleStr && children) {
            paperTitleStr = reactToText(children);
          }

          if (corpusId && paperTitleStr && id) {
            return (
              <InlinePaperChipWidgetWithEvidence
                {...rest}
                isShortName={true}
                paperTitle={paperTitleStr}
                corpusId={corpusId}
                fullTitle={fullTitle ?? 'Error: Paper Title Unkonwn'}
                id={id}
                evidences={
                  id2Snippets?.[id]?.map((snippet) => ({
                    text: snippet,
                  })) ?? []
                }
              />
            );
          } else {
            return null;
          }
        },
      },
    },
  };

  return (
    <div style={{ color: '#3a3a3a' }}>
      <DocumentContainer>
        <SectionContainer>
          <Markdown options={markdownOptions}>
            {`${section.text}
### References
${section.citations?.map((citation) => {
  console.log(citation)
  return `- <Paper corpusId="${citation.corpusId}" id="${citation.id}" paperTitle="${citation.anchorText}" fullTitle="${citation.fullTitle}" isShortName></Paper>: ${citation.snippets.join('... ')}`;
}).join('\n')}

### Disclaimer: What should I be cautious of when using features that employ generative AI?
Since text in these features is generated by a language model, it will not be free of errors, and the errors could be difficult to detect. Possible errors include: 
- Factual inaccuracies. Most of these will be subtle, but some may be serious factual errors 
- Awkwardly phrased answers
- Irrelevant information.

While we generally found the system to be accurate, you should verify the accuracy of generated text whenever possible.
`}
          </Markdown>
        </SectionContainer>
      </DocumentContainer>
    </div>
  );
};

const DocumentContainer = styled('div')`
`;

const SectionContainer = styled('div')`
  padding: 32px 32px;
  background: #eaeaea;
  border-radius: 6px;
`;
